_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SkinRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
  ROI_IMG_HEAD: 
    NAME: "RoiImgHead_Resnet"
    TYPE: "resnet50"
  SOFT_MASK:
    NUM: 5
    THETA: 0.95
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("skin10_train",)
  TEST: ("skin10_test",)
OUTPUT:
  TOPK_ACC: 3